2 Fixes
Fix ip checks in func_ipsettings
Fix partial greps func_setipsettings


Former-commit-id: a6f46601d3b0aa758d4f096f2a837c295ab47672 [formerly cf936aafd7a29f22b03c304c492b2fbd5b59e83f]
Former-commit-id: 59c0faf47fef26414423f39942eade9324b40a7c

diff --git a/rpmbuild/SOURCES/eFa-4.0.0/eFa/lib-eFa-Configure/func_ipsettings b/rpmbuild/SOURCES/eFa-4.0.0/eFa/lib-eFa-Configure/func_ipsettings
--- a/rpmbuild/SOURCES/eFa-4.0.0/eFa/lib-eFa-Configure/func_ipsettings
+++ b/rpmbuild/SOURCES/eFa-4.0.0/eFa/lib-eFa-Configure/func_ipsettings
@@ -33,7 +33,8 @@ func_ip-settings(){
                 1)  ipmenu=0
                     echo ""
                     read -p "Enter your new IP: " IP4
-                    if [[ -z "$IP4" || !(checkip4 $IP4) ]]; then echo "ERROR invalid ip address" && pause && menu=1; else
+                    checkip4 $IP4
+                    if [[ -z "$IP4" || $? -eq 1 ]]; then echo "ERROR invalid ip address" && pause && menu=1; else
                       func_setipsettings
                       menu=1
                     fi
@@ -41,7 +42,8 @@ func_ip-settings(){
                 2)  ipmenu=0
                     echo ""
                     read -p "Enter your new netmask: " NM4
-                    if [[ -z "$NM4" || !(checkip4 $NM4) ]]; then echo "ERROR invalid netmask" && pause && menu=1; else
+                    checkip4 $NM4
+                    if [[ -z "$NM4" || $? -eq 1 ]]; then echo "ERROR invalid netmask" && pause && menu=1; else
                       func_setipsettings
                       menu=1
                     fi
@@ -49,7 +51,8 @@ func_ip-settings(){
                 3)  ipmenu=0
                     echo ""
                     read -p "Enter your new gateway: " GW4
-                    if [[ -z "$GW4" || !(checkip4 $GW4) ]]; then echo "ERROR empty value" && pause && menu=1; else
+                    checkip4 $GW4
+                    if [[ -z "$GW4" || $? -eq 1 ]]; then echo "ERROR empty value" && pause && menu=1; else
                       func_setipsettings
                       menu=1
                     fi
@@ -57,7 +60,8 @@ func_ip-settings(){
                 4)  ipmenu=0
                     echo ""
                     read -p "Enter your new IPv6 IP: " IP6
-                    if [[ -z "$IP6" || !(checkip6 $IP6) ]]; then echo "ERROR invalid ip address" && pause && menu=1; else
+                    checkip6 $IP6
+                    if [[ -z "$IP6" || $? -eq 1 ]]; then echo "ERROR invalid ip address" && pause && menu=1; else
                       func_setipsettings
                       menu=1
                     fi
@@ -73,7 +77,8 @@ func_ip-settings(){
                 6)  ipmenu=0
                     echo ""
                     read -p "Enter your new IPv6 Gateway: " GW6
-                    if [[ -z "$GW6" || !(checkip6 $GW6) ]]; then echo "ERROR invalid gateway address" && pause && menu=1; else
+                    checkip6 $GW6
+                    if [[ -z "$GW6" || $? -eq 1 ]]; then echo "ERROR invalid gateway address" && pause && menu=1; else
                       func_setipsettings
                       menu=1
                     fi
