Add dhcp/static toggling to eFa-Configure

diff --git a/rpmbuild/SOURCES/eFa-4.0.0/eFa/lib-eFa-Configure/func_ipsettings b/rpmbuild/SOURCES/eFa-4.0.0/eFa/lib-eFa-Configure/func_ipsettings
--- a/rpmbuild/SOURCES/eFa-4.0.0/eFa/lib-eFa-Configure/func_ipsettings
+++ b/rpmbuild/SOURCES/eFa-4.0.0/eFa/lib-eFa-Configure/func_ipsettings
@@ -9,17 +9,19 @@ func_ip-settings(){
       func_getipsettings
       func_echo-header
       echo -e "Current IP settings for $INTERFACE are:"
-      echo -e " 1) IP                   :  $IP4"
-      echo -e " 2) Netmask              :  $NM4"
-      echo -e " 3) Gateway              :  $GW4"
-      echo -e " 4) IPv6 IP              :  $IP6"
-      echo -e " 5) IPv6 Prefix          :  $PF6"
-      echo -e " 6) IPv6 Gateway         :  $GW6"
-      echo -e " 7) DNS Recursion        :  $RECURSIVEDNS"
-      echo -e " 8) Primary DNS          :  $DNS1"
-      echo -e " 9) Secondary DNS        :  $DNS2"
-      echo -e "10) Hostname             :  $HOSTNAME"
-      echo -e "11) Domain Name          :  $DOMAINNAME"
+      echo -e " 1) BOOTPROTO            :  $BOOTPROTO"
+      echo -e " 2) IPV6_AUTOCONF        :  $IPV6AUTOCONF"
+      echo -e " 3) IP                   :  $IP4"
+      echo -e " 4) Netmask              :  $NM4"
+      echo -e " 5) Gateway              :  $GW4"
+      echo -e " 6) IPv6 IP              :  $IP6"
+      echo -e " 7) IPv6 Prefix          :  $PF6"
+      echo -e " 8) IPv6 Gateway         :  $GW6"
+      echo -e " 9) DNS Recursion        :  $RECURSIVEDNS"
+      echo -e "10) Primary DNS          :  $DNS1"
+      echo -e "11) Secondary DNS        :  $DNS2"
+      echo -e "12) Hostname             :  $HOSTNAME"
+      echo -e "13) Domain Name          :  $DOMAINNAME"
       echo -e ""
       echo -e "e) Return to main menu"
       echo -e ""
@@ -32,62 +34,84 @@ func_ip-settings(){
       case $choice in
                 1)  ipmenu=0
                     echo ""
-                    read -p "Enter your new IP: " IP4
-                    checkip4 $IP4
-                    if [[ -z "$IP4" || $? -eq 1 ]]; then echo "ERROR invalid ip address" && pause && menu=1; else
-                      func_setipsettings
-                      menu=1
+                    read -p "Do you want to use DHCP? (y/N): " ASKPROTO
+                    if [[ -z $ASKPROTO || $ASKPROTO =~ /^nN$/ ]]; then
+                       BOOTPROTO="none"
+                    elif [[ $ASKPROTO =~ /^yY$/ ]]; then
+                       BOOTPROTO="dhcp"
+                    else
+                      echo "ERROR invalid choice" && pause && menu=1
                     fi
                     ;;
                 2)  ipmenu=0
                     echo ""
-                    read -p "Enter your new netmask: " NM4
-                    checkip4 $NM4
-                    if [[ -z "$NM4" || $? -eq 1 ]]; then echo "ERROR invalid netmask" && pause && menu=1; else
-                      func_setipsettings
-                      menu=1
+                    read -p "Do you want to use IPV6 Auto Configuration? (y/N): " ASKAUTO
+                    if [[ -z $ASKAUTO || $ASKAUTO =~ /^nN$/ ]]; then
+                       IPV6AUTOCONF="no"
+                    elif [[ $ASKAUTO =~ /^yY$/ ]]; then
+                       IPV6AUTOCONF="yes"
+                    else
+                      echo "ERROR invalid choice" && pause && menu=1
                     fi
                     ;;
                 3)  ipmenu=0
                     echo ""
-                    read -p "Enter your new gateway: " GW4
-                    checkip4 $GW4
-                    if [[ -z "$GW4" || $? -eq 1 ]]; then echo "ERROR empty value" && pause && menu=1; else
+                    read -p "Enter your new IP: " IP4
+                    checkip4 $IP4
+                    if [[ -n "$IP4" && $? -eq 1 ]]; then echo "ERROR invalid ip address" && pause && menu=1; else
                       func_setipsettings
                       menu=1
                     fi
                     ;;
                 4)  ipmenu=0
                     echo ""
-                    read -p "Enter your new IPv6 IP: " IP6
-                    checkip6 $IP6
-                    if [[ -z "$IP6" || $? -eq 1 ]]; then echo "ERROR invalid ip address" && pause && menu=1; else
+                    read -p "Enter your new netmask: " NM4
+                    checkip4 $NM4
+                    if [[ -n "$NM4" && $? -eq 1 ]]; then echo "ERROR invalid netmask" && pause && menu=1; else
                       func_setipsettings
                       menu=1
                     fi
                     ;;
                 5)  ipmenu=0
                     echo ""
-                    read -p "Enter your new IPv6 Prefix: " PF6
-                    if [[ -z "$PF6" || !($PF6 =~ ^[0-9]{1,3}$ && $PF6 -ge 1 && $PF6 -le 128 && $(( $PF6 & ($PF6 - 1) )) -eq 0) ]]; then echo "ERROR invalid ipv6 prefix" && pause && menu=1; else
+                    read -p "Enter your new gateway: " GW4
+                    checkip4 $GW4
+                    if [[ -n "$GW4" && $? -eq 1 ]]; then echo "ERROR empty value" && pause && menu=1; else
                       func_setipsettings
                       menu=1
                     fi
                     ;;
                 6)  ipmenu=0
                     echo ""
-                    read -p "Enter your new IPv6 Gateway: " GW6
-                    checkip6 $GW6
-                    if [[ -z "$GW6" || $? -eq 1 ]]; then echo "ERROR invalid gateway address" && pause && menu=1; else
+                    read -p "Enter your new IPv6 IP: " IP6
+                    checkip6 $IP6
+                    if [[ -n "$IP6" && $? -eq 1 ]]; then echo "ERROR invalid ip address" && pause && menu=1; else
                       func_setipsettings
                       menu=1
                     fi
                     ;;
                 7)  ipmenu=0
+                    echo ""
+                    read -p "Enter your new IPv6 Prefix: " PF6
+                    if [[ -n "$PF6" && !($PF6 =~ ^[0-9]{1,3}$ && $PF6 -ge 1 && $PF6 -le 128 && $(( $PF6 & ($PF6 - 1) )) -eq 0) ]]; then echo "ERROR invalid ipv6 prefix" && pause && menu=1; else
+                      func_setipsettings
+                      menu=1
+                    fi
+                    ;;
+                8)  ipmenu=0
+                    echo ""
+                    read -p "Enter your new IPv6 Gateway: " GW6
+                    checkip6 $GW6
+                    if [[ -n "$GW6" && $? -eq 1 ]]; then echo "ERROR invalid gateway address" && pause && menu=1; else
+                      func_setipsettings
+                      menu=1
+                    fi
+                    ;;
+                9)  ipmenu=0
                     func_ask-recursion
                     menu=1
                     ;;
-                8)  ipmenu=0
+               10)  ipmenu=0
                     echo ""
                     if [ "$RECURSIVEDNS" == "ENABLED" ]; then 
                       echo "ERROR: DNS Recursion is enabled.  Disable recursion to set DNS"
@@ -100,7 +124,7 @@ func_ip-settings(){
                       fi
                     fi
                     ;;
-                9)  ipmenu=0
+               11)  ipmenu=0
                     echo ""
                     if [ "$RECURSIVEDNS" == "ENABLED" ]; then 
                       echo "ERROR: DNS Recursion is enabled.  Disable recursion to set DNS"
@@ -113,7 +137,7 @@ func_ip-settings(){
                       fi
                     fi
                     ;;
-                10) ipmenu=0
+                12) ipmenu=0
                     echo ""
                     read -p "Enter your new HOSTNAME: " HOSTNAME
                     if [ -z "$HOSTNAME" ]; then echo "ERROR empty value" && pause && menu=1; else
@@ -121,7 +145,7 @@ func_ip-settings(){
                       menu=1
                     fi
                     ;;
-                11) ipmenu=0
+                13) ipmenu=0
                     echo ""
                     read -p "Enter your new DOMAIN NAME: " DOMAINNAME
                     if [ -z "$DOMAINNAME" ]; then echo "ERROR empty value" && pause && menu=1; else
