3 eFa-Post-Init Updates
Verify Internet connectivity
Run some tasks asynchronously
Error handling for reload/restarts

diff --git a/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init b/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init
--- a/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init
+++ b/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init
@@ -24,28 +24,59 @@
 # Don't run if lock is present
 [[ -f /var/run/eFa-Post-Init.lock ]] && exit 0
 
+# Do we have Internet access?
+wget -q --tries=3 --timeout=20 --spider https://mirrors.efa-project.org
+if [[ $? -ne 0 ]]; then
+  logger -p user.warn "eFa Post Init: No Internet access detected!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
+  exit 1
+fi
+
 touch /var/run/eFa-Post-Init.lock
 
 # Remove eFaInit config
 rm -f /etc/httpd/conf.d/eFaInit.conf
 
+freshclam
+
+/etc/cron.daily/mailscanner &
+
+/usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php &
+
+/usr/bin/mailwatch/tools/Cron_jobs/mailwatch_update_sarules.php &
+
 openssl dhparam -out /etc/postfix/ssl/dhparam.pem 2048
 postconf -e "smtpd_tls_dh1024_param_file = /etc/postfix/ssl/dhparam.pem"
 cat /etc/postfix/ssl/dhparam.pem >> /etc/pki/tls/certs/localhost.crt
 
-freshclam
-
-/etc/cron.daily/mailscanner
-
-/usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php
-
-/usr/bin/mailwatch/tools/Cron_jobs/mailwatch_update_sarules.php
-
 # Reload daemons
 systemctl reload postfix
+if [[ $? -ne 0 ]]; then
+  # Error!  Try again...
+  logger -p user.warn "eFa Post Init: Postfix reload failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
+  rm -f /var/run/eFa-Post-Init.lock
+  exit 1
+fi
 systemctl reload httpd
+if [[ $? -ne 0 ]]; then
+  # Error!  Try again...
+  logger -p user.warn "eFa Post Init: Apache reload failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
+  rm -f /var/run/eFa-Post-Init.lock
+  exit 1
+fi
 systemctl restart clamd@scan
+if [[ $? -ne 0 ]]; then
+  # Error!  Try again...
+  logger -p user.warn "eFa Post Init: Clamd restart failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
+  rm -f /var/run/eFa-Post-Init.lock
+  exit 1
+fi
 systemctl restart sqlgrey
+if [[ $? -ne 0 ]]; then
+  # Error!  Try again...
+  logger -p user.warn "eFa Post Init: sqlgrey restart failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
+  rm -f /var/run/eFa-Post-Init.lock
+  exit 1
+fi
 
 # Spawn mta relay stats watchers
 /etc/cron.hourly/mailwatch_relay.sh
