3 Updates
Cleanup unused code in eFa-Commit
Refactor eFa-Post-Init for efficiency
Cleanup eFaInitController.php


Former-commit-id: d6b2932473b58092901bfe600142304579e0f120 [formerly e734bc6a935f8e8013c8beba52a63408054edc37]
Former-commit-id: f3a91ea00ef7b8f9b917ebc841ed4061d53c8e2b

diff --git a/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init b/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init
--- a/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init
+++ b/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init
@@ -18,6 +18,10 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #-----------------------------------------------------------------------------#
 
+############################## PRECHECK #######################################
+# Things that must be done before initializing
+###############################################################################
+
 # Don't run if reboot is pending
 [[ -f /reboot.system ]] && exit 0
 
@@ -27,20 +31,35 @@
 # Reset footer
 sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...INITIALIZING SYSTEM, PLEASE WAIT... ';" /var/www/html/mailscanner/functions.php
 
+# Remove eFaInit config if present
+[[ -f /etc/httpd/conf.d/eFaInit.conf ]] && rm -f /etc/httpd/conf.d/eFaInit.conf
+
 # Do we have Internet access?
 wget -q --tries=3 --timeout=20 --spider https://mirrors.efa-project.org
 if [[ $? -ne 0 ]]; then
   logger -p user.warn "eFa Post Init: No Internet access detected!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
-	sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK INTERNET ACCESS... ';" /var/www/html/mailscanner/functions.php
+  sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK INTERNET ACCESS... ';" /var/www/html/mailscanner/functions.php
   exit 1
 fi
 
+# Precheck passes, create lock file
 touch /var/run/eFa-Post-Init.lock
 
-# Remove eFaInit config
-[[ -f /etc/httpd/conf.d/eFaInit.conf ]] && rm -f /etc/httpd/conf.d/eFaInit.conf
+############################## EARLY PHASE ###################################
+# Tasks that must happen before allowing email to relay
+##############################################################################
 
-# Asynchronous tasks first
+# Early daemon restart
+systemctl restart sqlgrey
+if [[ $? -ne 0 ]]; then
+  # Error!  Try again...
+  logger -p user.warn "eFa Post Init: sqlgrey restart failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
+  sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK SQLGREY... ';" /var/www/html/mailscanner/functions.php
+  rm -f /var/run/eFa-Post-Init.lock
+  exit 1
+fi
+
+# Early asynchronous tasks
 /etc/cron.daily/mailscanner &
 
 /usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php &
@@ -49,45 +68,14 @@ touch /var/run/eFa-Post-Init.lock
 
 /usr/sbin/clamav-unofficial-sigs.sh &
 
-# Synchronous tasks
+# Early synchronous tasks
 freshclam
 
-if [[ ! -f /etc/postfix/ssl/dhparam.pem ]]; then
-  openssl dhparam -out /etc/postfix/ssl/dhparam.pem 2048
-  postconf -e "smtpd_tls_dh1024_param_file = /etc/postfix/ssl/dhparam.pem"
-  cat /etc/postfix/ssl/dhparam.pem >> /etc/pki/tls/certs/localhost.crt
-fi
-
-# Reload daemons
-systemctl reload postfix
-if [[ $? -ne 0 ]]; then
-  # Error!  Try again...
-  logger -p user.warn "eFa Post Init: Postfix reload failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
-  sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK POSTFIX... ';" /var/www/html/mailscanner/functions.php
-  rm -f /var/run/eFa-Post-Init.lock
-  exit 1
-fi
-systemctl reload httpd
-if [[ $? -ne 0 ]]; then
-  # Error!  Try again...
-  logger -p user.warn "eFa Post Init: Apache reload failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
-  sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK APACHE... ';" /var/www/html/mailscanner/functions.php
-  rm -f /var/run/eFa-Post-Init.lock
-  exit 1
-fi
 systemctl restart clamd@scan
 if [[ $? -ne 0 ]]; then
   # Error!  Try again...
   logger -p user.warn "eFa Post Init: Clamd restart failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
   sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK CLAMD... ';" /var/www/html/mailscanner/functions.php
-  rm -f /var/run/eFa-Post-Init.lock
-  exit 1
-fi
-systemctl restart sqlgrey
-if [[ $? -ne 0 ]]; then
-  # Error!  Try again...
-  logger -p user.warn "eFa Post Init: sqlgrey restart failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
-  sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK SQLGREY... ';" /var/www/html/mailscanner/functions.php
   rm -f /var/run/eFa-Post-Init.lock
   exit 1
 fi
@@ -103,6 +91,40 @@ echo "* * * * * root /usr/sbin/eFa-Monitor-cron >/dev/null 2>&1" > /etc/cron.d/e
 
 # Remove INITIALIZING message
 sed -i "/^    echo ' running on '/ c\    echo ' running on ' . efa_version();" /var/www/html/mailscanner/functions.php
+
+############################## LATE PHASE ###################################
+# Tasks that are not needed for email to relay
+#############################################################################
+
+# Late Asynchronous tasks
+# Todo: enable for post init
+# /usr/bin/sa-learn --spam /usr/src/eFa/spamassassin/gtube.txt &
+
+# Late Synchronous tasks
+if [[ ! -f /etc/postfix/ssl/dhparam.pem ]]; then
+  openssl dhparam -out /etc/postfix/ssl/dhparam.pem 2048
+  postconf -e "smtpd_tls_dh1024_param_file = /etc/postfix/ssl/dhparam.pem"
+  cat /etc/postfix/ssl/dhparam.pem >> /etc/pki/tls/certs/localhost.crt
+fi
+  
+# Late Reload daemons
+systemctl reload postfix
+if [[ $? -ne 0 ]]; then
+  # Error!  Try again...
+  logger -p user.warn "eFa Post Init: Postfix reload failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
+  sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK POSTFIX... ';" /var/www/html/mailscanner/functions.php
+  rm -f /var/run/eFa-Post-Init.lock
+  exit 1
+fi
+systemctl reload httpd
+if [[ $? -ne 0 ]]; then
+  # Error!  Try again...
+  logger -p user.warn "eFa Post Init: Apache reload failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
+  # If apache is dead, this won't matter
+  #sed -i "/^    echo mailwatch_version/a \    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK APACHE... ';" /var/www/html/mailscanner/functions.php
+  rm -f /var/run/eFa-Post-Init.lock
+  exit 1
+fi
 
 rm -f /etc/cron.d/efapostinit
 rm -f /var/run/eFa-Post-Init.lock
