Performance optimization for post init
Former-commit-id: 80b514f976d1a6987aa49050de84b8bb71e7b287

diff --git a/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init b/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init
--- a/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init
+++ b/rpmbuild/SOURCES/eFa-4.0.0/eFa/eFa-Post-Init
@@ -102,17 +102,18 @@ fi
 # Early synchronous tasks
 
 if [[ ! -f /var/lib/clamav/main.cvd ]]; then
-  freshclam
-fi
+  systemctl stop clamd@scan
 
-systemctl enable clamd@scan
-systemctl start clamd@scan
-if [[ $? -ne 0 ]]; then
-  # Error!  Try again...
-  logger -p user.warn "eFa Post Init: Clamd restart failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
-  sed -i "/^    echo ' running on ' . efa_version()/ c\    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK CLAMD... ';" /var/www/html/mailscanner/functions.php
-  rm -f /var/run/eFa-Post-Init.lock
-  exit 1
+  freshclam
+
+  systemctl start clamd@scan
+  if [[ $? -ne 0 ]]; then
+    # Error!  Try again...
+    logger -p user.warn "eFa Post Init: Clamd restart failed!  Please fix me to finish initializing eFa.  Retrying in 1 minute..."
+    sed -i "/^    echo ' running on ' . efa_version()/ c\    echo ' running on ' . efa_version() . ' ...ERROR INITIALIZATING, CHECK CLAMD... ';" /var/www/html/mailscanner/functions.php
+    rm -f /var/run/eFa-Post-Init.lock
+    exit 1
+  fi
 fi
 
 # Spawn mta relay stats watchers
