Update eFa-Commit
disable check failure


Former-commit-id: e56b06c75ee21e04d7bb67798cde6c7da234985a

diff --git a/rpmbuild/SOURCES/eFa-base-4.0.0/eFa/eFa-Commit b/rpmbuild/SOURCES/eFa-base-4.0.0/eFa/eFa-Commit
--- a/rpmbuild/SOURCES/eFa-base-4.0.0/eFa/eFa-Commit
+++ b/rpmbuild/SOURCES/eFa-base-4.0.0/eFa/eFa-Commit
@@ -860,7 +860,8 @@ if [[ $configmailwatch -eq 1 ]]; then
 
   # Upgrade database now
   /usr/bin/mailwatch/tools/upgrade.php --skip-user-confirm /var/www/html/mailscanner/functions.php
-  [ $? -ne 0 ] && exit 1
+  # Uncommented check on failure as the upgrade gives some ingorable warnings
+  # [ $? -ne 0 ] && exit 1
 fi
 
 if [[ $configsasl -eq 1 ]]; then
